export const briefPage = {
  meta: {
    title: "Share your brief",
    description: "Tell us about the home you have in mind. An advisor will review it personally and come back with the first homes worth considering.",
  },
  title: "What are you looking for?",
  intro:
    "Tell us a little about the home you have in mind. An advisor will review it personally and come back with the first homes worth considering.",
  describe: {
    label: "Describe it in your own words",
    hint: "Optional. We'll use it to fill in the form for you — you can adjust anything.",
    placeholder: "e.g. A large 4 BHK for my family, somewhere quiet and green, with reasonable access to Whitefield. Budget around ₹6 Cr.",
    button: "Fill in the form from this",
    applied: "We've filled in what we understood. Please check each step.",
    nothing: "We couldn't pick out specific details — please use the form below.",
  },
  enquiringAbout: "You're asking about",
  labels: {
    propertyType: "Home type",
    configurations: "Configuration",
    minSizeSqft: "Size preference",
    minSizeHint: "Minimum, in sq ft",
    possession: "Possession",
    budget: "Budget",
    areas: "Preferred areas",
    areasHint: "Choose any",
    openToSuggestions: "Open to suggestions",
    priorities: "What matters most",
    prioritiesHint: "Choose up to three",
    notes: "Anything else we should know?",
    name: "Name",
    phone: "Phone",
    phoneHint: "Indian numbers as usual; include the country code (e.g. +44) if you're outside India",
    email: "Email",
    basedIn: "Currently based in",
    contactPref: "Preferred contact",
    bestTime: "Best time to reach you",
    consent: "I agree to Floors & Pillars contacting me about this brief, as described in the",
    privacyLink: "privacy notice",
  },
  requiredNote: "Everything is required unless marked optional.",
  continue: "Continue",
  back: "Back",
  submit: "Curate my shortlist",
  submitting: "Sending…",
  errorSummary: "Please check the highlighted fields.",
  serverError: "We couldn't send your brief just now. Please try again in a moment.",
  rateLimited: "We've received several briefs from this connection. Please wait a few minutes and try again.",
};

export const thankYouPage = {
  meta: { title: "Thank you", description: "Your brief has reached us." },
  title: "Thank you.",
  body: (responseTime: string) => `An advisor will review your brief and be in touch within ${responseTime}.`,
  nextTitle: "What happens next",
  next: [
    { name: "We read it properly", text: "An advisor reads your brief in full and notes anything worth clarifying." },
    { name: "A short conversation", text: "We call or message you at the time you chose, to understand what the form can't capture." },
    { name: "Your first shortlist", text: "We come back with the first homes worth considering, each with a note on why." },
  ],
  matchesTitle: "While you wait: from our collection",
  matchesIntro: "A first look at homes in our current collection that sit close to your brief. Your advisor will go much further.",
  journalTitle: "Reading for the meantime",
};
